# Sklearn Statistics - Part 2: Preprocessing

This notebook covers data preprocessing techniques using sklearn.

**Topics covered:**
- StandardScaler (z-score normalization)
- MinMaxScaler (0-1 scaling)
- RobustScaler (median/IQR scaling)
- Normalization (L1, L2)
- Imputation (handling missing values)

**Problems:** 17 (Easy: 1-6, Medium: 7-12, Hard: 13-17)

In [ ]:
# ============================================
# SETUP - Run this cell first!
# ============================================
import sys
sys.path.insert(0, '..')
from utils.checker import check

print("Checker loaded! Now import the libraries you need.")

---
## Problem 0: Import Required Libraries
**Difficulty:** Easy

### Concept
Before preprocessing data, you need to import the necessary libraries. NumPy and Pandas handle data structures, while sklearn provides preprocessing utilities.

### Syntax
```python
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, Normalizer, MaxAbsScaler, PowerTransformer
from sklearn.impute import SimpleImputer
```

### Task
Import the following:
- NumPy as `np`
- Pandas as `pd`
- From sklearn.preprocessing: StandardScaler, MinMaxScaler, RobustScaler, Normalizer, MaxAbsScaler, PowerTransformer
- From sklearn.impute: SimpleImputer

### Expected Properties
- All modules and classes should be importable

In [ ]:
# Your solution:


In [ ]:
# Verification
check.is_true('np' in dir(), "P0a: NumPy imported", "Import numpy as np")
check.is_true('pd' in dir(), "P0b: Pandas imported", "Import pandas as pd")
check.is_true('StandardScaler' in dir(), "P0c: StandardScaler imported", "Import StandardScaler from sklearn.preprocessing")
check.is_true('SimpleImputer' in dir(), "P0d: SimpleImputer imported", "Import SimpleImputer from sklearn.impute")

---
## Problem 1: StandardScaler - Fit and Transform
**Difficulty:** Easy

### Concept
StandardScaler transforms features to have zero mean and unit variance (z-score normalization). This is crucial for algorithms sensitive to feature scales like SVM, KNN, and neural networks.

Formula: `z = (x - mean) / std`

### Syntax
```python
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Or in two steps
scaler.fit(X)
X_scaled = scaler.transform(X)
```

### Example
```python
>>> X = [[0], [5], [10]]
>>> scaler = StandardScaler()
>>> scaler.fit_transform(X)
array([[-1.22],
       [ 0.  ],
       [ 1.22]])
```

### Task
Apply StandardScaler to the data `[[10], [20], [30], [40], [50]]`. Store the scaled result in `X_scaled`.

### Expected Properties
- `X_scaled` should be a numpy array
- Mean of scaled data should be approximately 0
- Standard deviation of scaled data should be approximately 1

In [ ]:
# Your solution:
X = np.array([[10], [20], [30], [40], [50]])
X_scaled = None

In [ ]:
# Verification
check.is_not_none(X_scaled, "P1: Not None")
check.is_type(X_scaled, np.ndarray, "P1: Type check")
check.has_shape(X_scaled, (5, 1), "P1: Correct shape")
check.mean_is_close(X_scaled, 0.0, "P1a: Mean is 0", tolerance=0.01)
check.std_is_close(X_scaled, 1.0, "P1b: Std is 1", tolerance=0.01)

---
## Problem 2: MinMaxScaler - Scale to 0-1
**Difficulty:** Easy

### Concept
MinMaxScaler transforms features to a fixed range, typically [0, 1]. This is useful when features need to be bounded, such as for neural network inputs or when you want to preserve zero entries in sparse data.

Formula: `X_scaled = (X - X.min) / (X.max - X.min)`

### Syntax
```python
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()  # Default range [0, 1]
X_scaled = scaler.fit_transform(X)
```

### Example
```python
>>> X = [[0], [5], [10]]
>>> scaler = MinMaxScaler()
>>> scaler.fit_transform(X)
array([[0. ],
       [0.5],
       [1. ]])
```

### Task
Apply MinMaxScaler to scale data to the range [0, 1]. Store in `X_minmax`.

### Expected Properties
- `X_minmax` should be a numpy array
- Minimum value should be 0
- Maximum value should be 1

In [ ]:
# Your solution:
X = np.array([[10], [20], [30], [40], [50]])
X_minmax = None

In [ ]:
# Verification
check.is_not_none(X_minmax, "P2: Not None")
check.is_type(X_minmax, np.ndarray, "P2: Type check")
check.has_shape(X_minmax, (5, 1), "P2: Correct shape")
check.min_value_is(X_minmax, 0.0, "P2a: Min is 0")
check.max_value_is(X_minmax, 1.0, "P2b: Max is 1")

---
## Problem 3: MinMaxScaler - Custom Range
**Difficulty:** Easy

### Concept
MinMaxScaler can scale to any custom range using the `feature_range` parameter. This is useful when you need specific bounds, like [-1, 1] for certain activation functions.

### Syntax
```python
scaler = MinMaxScaler(feature_range=(-1, 1))
X_scaled = scaler.fit_transform(X)
```

### Example
```python
>>> X = [[0], [5], [10]]
>>> scaler = MinMaxScaler(feature_range=(-1, 1))
>>> scaler.fit_transform(X)
array([[-1.],
       [ 0.],
       [ 1.]])
```

### Task
Scale data to range [-1, 1] using MinMaxScaler with `feature_range=(-1, 1)`. Store in `X_custom`.

### Expected Properties
- `X_custom` should be a numpy array
- Minimum value should be -1
- Maximum value should be 1

In [ ]:
# Your solution:
X = np.array([[10], [20], [30], [40], [50]])
X_custom = None

In [ ]:
# Verification
check.is_not_none(X_custom, "P3: Not None")
check.is_type(X_custom, np.ndarray, "P3: Type check")
check.min_value_is(X_custom, -1.0, "P3a: Min is -1")
check.max_value_is(X_custom, 1.0, "P3b: Max is 1")

---
## Problem 4: Get Scaler Parameters
**Difficulty:** Easy

### Concept
After fitting a scaler, you can access the learned parameters. For StandardScaler, `mean_` contains the mean and `scale_` contains the standard deviation used for transformation.

### Syntax
```python
scaler = StandardScaler()
scaler.fit(X)
mean = scaler.mean_      # Mean of each feature
std = scaler.scale_      # Std of each feature
```

### Example
```python
>>> X = [[10], [20], [30]]
>>> scaler = StandardScaler()
>>> scaler.fit(X)
>>> scaler.mean_
array([20.])
>>> scaler.scale_
array([8.16...])
```

### Task
Fit a StandardScaler on the data and extract the mean and standard deviation. Store them in `mean_` and `std_`.

### Expected Properties
- `mean_` should be an array with the mean value
- `std_` should be an array with the standard deviation
- Mean should be 30 (middle of 10-50)
- Std should be approximately 14.14

In [ ]:
# Your solution:
X = np.array([[10], [20], [30], [40], [50]])
scaler = StandardScaler()
scaler.fit(X)

mean_ = None
std_ = None

In [ ]:
# Verification
check.is_not_none(mean_, "P4a: Mean not None")
check.is_not_none(std_, "P4b: Std not None")
check.is_type(mean_, np.ndarray, "P4c: Mean type check")
check.is_type(std_, np.ndarray, "P4d: Std type check")
check.is_true(abs(mean_[0] - 30.0) < 0.01, "P4e: Correct mean", "Mean should be 30")
check.value_in_range(std_[0], 14, 15, "P4f: Reasonable std")

---
## Problem 5: Simple Imputer - Mean
**Difficulty:** Easy

### Concept
Missing values (NaN) must be handled before applying most machine learning algorithms. SimpleImputer fills missing values with a statistic (mean, median, most frequent, or constant).

### Syntax
```python
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')  # or 'median', 'most_frequent', 'constant'
X_imputed = imputer.fit_transform(X)
```

### Example
```python
>>> X = [[1], [2], [np.nan], [4]]
>>> imputer = SimpleImputer(strategy='mean')
>>> imputer.fit_transform(X)
array([[1. ],
       [2. ],
       [2.33],  # Mean of 1, 2, 4
       [4. ]])
```

### Task
Fill missing values with the mean using SimpleImputer. Store in `X_imputed`.

### Expected Properties
- `X_imputed` should be a numpy array
- Should have no NaN values
- The missing value should be replaced with the mean of non-missing values (3.0)

In [ ]:
# Your solution:
X = np.array([[1], [2], [np.nan], [4], [5]])
X_imputed = None

In [ ]:
# Verification
check.is_not_none(X_imputed, "P5: Not None")
check.is_type(X_imputed, np.ndarray, "P5: Type check")
check.has_shape(X_imputed, (5, 1), "P5: Correct shape")
check.is_true(not np.any(np.isnan(X_imputed)), "P5a: No NaN values", "Should have no missing values")
check.is_true(abs(X_imputed[2, 0] - 3.0) < 0.01, "P5b: Correct imputation", "Missing value should be replaced with mean")

---
## Problem 6: Simple Imputer - Median
**Difficulty:** Easy

### Concept
The median strategy is more robust to outliers than the mean. When data has extreme values, median imputation preserves the central tendency better.

### Syntax
```python
imputer = SimpleImputer(strategy='median')
X_imputed = imputer.fit_transform(X)
```

### Example
```python
>>> X = [[1], [2], [np.nan], [100]]  # 100 is outlier
>>> imputer = SimpleImputer(strategy='median')
>>> imputer.fit_transform(X)
array([[  1.],
       [  2.],
       [  1.5],  # Median of 1, 2, 100 = 2
       [100.]])
```

### Task
Fill missing values with the median. Note the outlier value 100. Store in `X_imputed`.

### Expected Properties
- `X_imputed` should be a numpy array
- Should have no NaN values
- Missing value should be replaced with median (3.0)

In [ ]:
# Your solution:
X = np.array([[1], [2], [np.nan], [4], [100]])  # 100 is outlier
X_imputed = None

In [ ]:
# Verification
check.is_not_none(X_imputed, "P6: Not None")
check.is_type(X_imputed, np.ndarray, "P6: Type check")
check.is_true(not np.any(np.isnan(X_imputed)), "P6a: No NaN values", "Should have no missing values")
check.is_true(abs(X_imputed[2, 0] - 3.0) < 0.01, "P6b: Correct median imputation", "Should use median")

---
## Problem 7: RobustScaler
**Difficulty:** Medium

### Concept
RobustScaler uses the median and IQR (Interquartile Range) instead of mean and std. This makes it robust to outliers, as extreme values don't affect the median and IQR as much as they affect mean and std.

Formula: `X_scaled = (X - median) / IQR`

### Syntax
```python
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()
X_scaled = scaler.fit_transform(X)
```

### Example
```python
>>> X = [[1], [2], [3], [100]]  # 100 is outlier
>>> scaler = RobustScaler()
>>> scaler.fit_transform(X)
# Outlier doesn't dominate the scaling
```

### Task
Apply RobustScaler to data that contains an outlier (100). Store in `X_robust`.

### Expected Properties
- `X_robust` should be a numpy array
- Should have same shape as input
- Median should map to approximately 0

In [ ]:
# Your solution:
X = np.array([[1], [2], [3], [4], [5], [100]])  # 100 is outlier
X_robust = None

In [ ]:
# Verification
check.is_not_none(X_robust, "P7: Not None")
check.is_type(X_robust, np.ndarray, "P7: Type check")
check.has_shape(X_robust, (6, 1), "P7: Correct shape")

---
## Problem 8: Scale Multiple Features
**Difficulty:** Medium

### Concept
StandardScaler works on each feature (column) independently. When you have multiple features with different scales, StandardScaler normalizes each one separately.

### Syntax
```python
# X is 2D array with multiple columns
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
```

### Example
```python
>>> X = [[1, 100],
...      [2, 200],
...      [3, 300]]
>>> scaler = StandardScaler()
>>> scaler.fit_transform(X)
# Each column scaled independently
```

### Task
Apply StandardScaler to the multi-feature dataset. Each feature has a different scale. Store in `X_scaled`.

### Expected Properties
- `X_scaled` should be a numpy array
- Should have shape (5, 3)
- Mean of each column should be approximately 0

In [ ]:
# Your solution:
X = np.array([
    [10, 100, 1000],
    [20, 200, 2000],
    [30, 300, 3000],
    [40, 400, 4000],
    [50, 500, 5000]
])

X_scaled = None

In [ ]:
# Verification
check.is_not_none(X_scaled, "P8: Not None")
check.is_type(X_scaled, np.ndarray, "P8: Type check")
check.has_shape(X_scaled, (5, 3), "P8: Correct shape")
check.mean_is_close(X_scaled.mean(axis=0), 0.0, "P8: Column means are 0", tolerance=0.01)

---
## Problem 9: L2 Normalization
**Difficulty:** Medium

### Concept
Normalization (not to be confused with standardization) scales each **sample** (row) to have unit norm. L2 normalization divides each sample by its Euclidean length, making each row have length 1.

This is useful for algorithms that measure similarity (like cosine similarity) or when the magnitude of vectors doesn't matter.

### Syntax
```python
from sklearn.preprocessing import Normalizer

normalizer = Normalizer(norm='l2')  # or 'l1', 'max'
X_normalized = normalizer.fit_transform(X)
```

### Example
```python
>>> X = [[3, 4]]  # Length = sqrt(3^2 + 4^2) = 5
>>> normalizer = Normalizer(norm='l2')
>>> normalizer.fit_transform(X)
array([[0.6, 0.8]])  # [3/5, 4/5]
```

### Task
Apply L2 normalization so each sample (row) has unit norm. Store in `X_normalized`.

### Expected Properties
- `X_normalized` should be a numpy array
- Each row should have L2 norm of 1
- Shape should be (3, 2)

In [ ]:
# Your solution:
X = np.array([
    [3, 4],
    [6, 8],
    [1, 0]
])

X_normalized = None

In [ ]:
# Verification
check.is_not_none(X_normalized, "P9: Not None")
check.is_type(X_normalized, np.ndarray, "P9: Type check")
check.has_shape(X_normalized, (3, 2), "P9: Correct shape")
_row_norms = np.linalg.norm(X_normalized, axis=1)
check.is_true(np.allclose(_row_norms, 1.0), "P9: Unit norm", "Each row should have L2 norm of 1")

---
## Problem 10: Imputer with Constant Value
**Difficulty:** Medium

### Concept
Sometimes you want to fill missing values with a specific constant rather than a statistic. This is useful when a specific value has semantic meaning (e.g., 0 for "no information").

### Syntax
```python
imputer = SimpleImputer(strategy='constant', fill_value=0)
X_imputed = imputer.fit_transform(X)
```

### Example
```python
>>> X = [[1], [np.nan], [3]]
>>> imputer = SimpleImputer(strategy='constant', fill_value=-999)
>>> imputer.fit_transform(X)
array([[   1.],
       [-999.],
       [   3.]])
```

### Task
Fill missing values with constant value 0. Store in `X_imputed`.

### Expected Properties
- `X_imputed` should be a numpy array
- Should have no NaN values
- Missing values should be replaced with 0

In [ ]:
# Your solution:
X = np.array([[1], [2], [np.nan], [4], [np.nan]])
X_imputed = None

In [ ]:
# Verification
check.is_not_none(X_imputed, "P10: Not None")
check.is_type(X_imputed, np.ndarray, "P10: Type check")
check.is_true(not np.any(np.isnan(X_imputed)), "P10a: No NaN values", "Should have no missing values")
check.is_true(X_imputed[2, 0] == 0.0, "P10b: First imputation", "Should be filled with 0")
check.is_true(X_imputed[4, 0] == 0.0, "P10c: Second imputation", "Should be filled with 0")

---
## Problem 11: Fit on Train, Transform Test
**Difficulty:** Medium

### Concept
**CRITICAL**: When preprocessing, you must fit the scaler ONLY on training data, then apply the same transformation to both train and test. This prevents data leakage - the test set must not influence the transformation parameters.

### Syntax
```python
scaler = StandardScaler()
scaler.fit(X_train)  # Learn parameters from train only
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)  # Apply same transformation
```

### Example
```python
>>> X_train = [[1], [2], [3]]
>>> X_test = [[4]]
>>> scaler = StandardScaler()
>>> scaler.fit(X_train)  # mean=2, std=1
>>> scaler.transform(X_test)  # Uses train's mean and std
```

### Task
Fit StandardScaler on training data, then transform both train and test sets. Store in `X_train_scaled` and `X_test_scaled`.

### Expected Properties
- Both should be numpy arrays
- Both should be transformed using the same parameters
- Test set values can be outside [-3, 3] range since they use train statistics

In [ ]:
# Your solution:
X_train = np.array([[10], [20], [30], [40], [50]])
X_test = np.array([[15], [25], [60]])  # Note: 60 is outside training range

X_train_scaled = None
X_test_scaled = None

In [ ]:
# Verification
check.is_not_none(X_train_scaled, "P11a: Train not None")
check.is_not_none(X_test_scaled, "P11b: Test not None")
check.is_type(X_train_scaled, np.ndarray, "P11c: Train type check")
check.is_type(X_test_scaled, np.ndarray, "P11d: Test type check")
check.has_shape(X_train_scaled, (5, 1), "P11e: Train shape")
check.has_shape(X_test_scaled, (3, 1), "P11f: Test shape")

---
## Problem 12: L1 Normalization
**Difficulty:** Medium

### Concept
L1 normalization scales each sample so that the sum of absolute values equals 1. This is useful for sparse data or when you want each sample to represent a probability distribution.

Formula: `X_normalized[i] = X[i] / sum(|X[i]|)`

### Syntax
```python
normalizer = Normalizer(norm='l1')
X_normalized = normalizer.fit_transform(X)
```

### Example
```python
>>> X = [[1, 2, 3]]  # Sum = 6
>>> normalizer = Normalizer(norm='l1')
>>> normalizer.fit_transform(X)
array([[0.167, 0.333, 0.5]])  # [1/6, 2/6, 3/6]
```

### Task
Apply L1 normalization so each row sums to 1 (in absolute value). Store in `X_l1`.

### Expected Properties
- `X_l1` should be a numpy array
- Sum of absolute values in each row should be 1
- Shape should be (2, 3)

In [ ]:
# Your solution:
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

X_l1 = None

In [ ]:
# Verification
check.is_not_none(X_l1, "P12: Not None")
check.is_type(X_l1, np.ndarray, "P12: Type check")
check.has_shape(X_l1, (2, 3), "P12: Correct shape")
_row_sums = np.abs(X_l1).sum(axis=1)
check.is_true(np.allclose(_row_sums, 1.0), "P12: L1 norm", "Each row should sum to 1 in absolute value")

---
## Problem 13: Inverse Transform
**Difficulty:** Hard

### Concept
After scaling, you can recover the original values using `inverse_transform()`. This is useful for interpreting results or converting predictions back to the original scale.

### Syntax
```python
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_original = scaler.inverse_transform(X_scaled)
```

### Example
```python
>>> X = [[10], [20], [30]]
>>> scaler = StandardScaler()
>>> X_scaled = scaler.fit_transform(X)
>>> scaler.inverse_transform(X_scaled)
array([[10.],
       [20.],
       [30.]])  # Back to original
```

### Task
Scale the data with StandardScaler, then use `inverse_transform()` to recover the original values. Store in `X_original`.

### Expected Properties
- `X_original` should be a numpy array
- Should match the original X values (within floating point precision)
- Shape should be (5, 1)

In [ ]:
# Your solution:
X = np.array([[10], [20], [30], [40], [50]])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_original = None

In [ ]:
# Verification
check.is_not_none(X_original, "P13: Not None")
check.is_type(X_original, np.ndarray, "P13: Type check")
check.has_shape(X_original, (5, 1), "P13: Correct shape")
check.is_true(np.allclose(X_original, X), "P13: Recovered original", "Should match original values")

---
## Problem 14: Impute Multiple Columns
**Difficulty:** Hard

### Concept
SimpleImputer can handle DataFrames with multiple columns, imputing each column independently. When working with DataFrames, you often want to preserve the column names and structure.

### Syntax
```python
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(df)
df_imputed = pd.DataFrame(X_imputed, columns=df.columns)
```

### Example
```python
>>> df = pd.DataFrame({'A': [1, np.nan, 3], 'B': [4, 5, np.nan]})
>>> imputer = SimpleImputer(strategy='mean')
>>> df_imputed = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)
```

### Task
Impute missing values in the DataFrame using mean strategy. Store as a DataFrame in `df_imputed`.

### Expected Properties
- `df_imputed` should be a DataFrame
- Should have no missing values
- Should have same shape as original (5, 3)

In [ ]:
# Your solution:
df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [10, np.nan, 30, 40, 50],
    'C': [100, 200, 300, np.nan, 500]
})

df_imputed = None

In [ ]:
# Verification
check.is_not_none(df_imputed, "P14: Not None")
check.is_type(df_imputed, pd.DataFrame, "P14: Type check")
check.has_shape(df_imputed, (5, 3), "P14: Correct shape")
check.has_no_nulls(df_imputed, "P14: No missing values")

---
## Problem 15: Compare Scalers
**Difficulty:** Hard

### Concept
Different scalers behave differently with outliers:
- StandardScaler: Sensitive to outliers (uses mean/std)
- MinMaxScaler: Very sensitive to outliers (uses min/max)
- RobustScaler: Robust to outliers (uses median/IQR)

Understanding these differences helps you choose the right scaler.

### Syntax
```python
X_standard = StandardScaler().fit_transform(X)
X_minmax = MinMaxScaler().fit_transform(X)
X_robust = RobustScaler().fit_transform(X)
```

### Example
```python
>>> X = [[1], [2], [3], [100]]  # Has outlier
>>> # StandardScaler will be affected by 100
>>> # RobustScaler will handle it better
```

### Task
Apply all three scalers to data with an outlier. Store results in `X_standard`, `X_minmax`, and `X_robust`.

### Expected Properties
- All three should be numpy arrays
- All should have shape (6, 1)
- RobustScaler will handle the outlier (1000) better than the others

In [ ]:
# Your solution:
X = np.array([[1], [2], [3], [4], [5], [1000]])  # Has outlier

X_standard = None
X_minmax = None
X_robust = None

In [ ]:
# Verification
check.is_not_none(X_standard, "P15a: Standard not None")
check.is_not_none(X_minmax, "P15b: MinMax not None")
check.is_not_none(X_robust, "P15c: Robust not None")
check.has_shape(X_standard, (6, 1), "P15d: Standard shape")
check.has_shape(X_minmax, (6, 1), "P15e: MinMax shape")
check.has_shape(X_robust, (6, 1), "P15f: Robust shape")

---
## Problem 16: MaxAbsScaler
**Difficulty:** Hard

### Concept
MaxAbsScaler scales each feature by dividing by the maximum absolute value. This scales data to the range [-1, 1] while preserving sparsity (zeros remain zeros). Useful for sparse data.

Formula: `X_scaled = X / max(|X|)`

### Syntax
```python
from sklearn.preprocessing import MaxAbsScaler

scaler = MaxAbsScaler()
X_scaled = scaler.fit_transform(X)
```

### Example
```python
>>> X = [[-10], [5], [20]]
>>> scaler = MaxAbsScaler()
>>> scaler.fit_transform(X)
array([[-0.5],  # -10/20
       [ 0.25], #   5/20
       [ 1.  ]]) #  20/20
```

### Task
Apply MaxAbsScaler to scale data to [-1, 1] based on maximum absolute value. Store in `X_maxabs`.

### Expected Properties
- `X_maxabs` should be a numpy array
- Maximum absolute value should be 1.0
- Values should be in range [-1, 1]

In [ ]:
# Your solution:
X = np.array([[-10], [5], [20], [-5], [10]])
X_maxabs = None

In [ ]:
# Verification
check.is_not_none(X_maxabs, "P16: Not None")
check.is_type(X_maxabs, np.ndarray, "P16: Type check")
check.has_shape(X_maxabs, (5, 1), "P16: Correct shape")
check.is_true(abs(np.abs(X_maxabs).max() - 1.0) < 0.01, "P16: Max abs is 1", "Maximum absolute value should be 1")
check.all_values_in_range(X_maxabs, -1, 1, "P16: In range [-1, 1]")

---
## Problem 17: Power Transform (Yeo-Johnson)
**Difficulty:** Hard

### Concept
Power transformations make data more Gaussian-like (normal distribution). This is useful for many statistical methods that assume normality. Yeo-Johnson can handle both positive and negative values (unlike Box-Cox which requires positive values).

### Syntax
```python
from sklearn.preprocessing import PowerTransformer

pt = PowerTransformer(method='yeo-johnson')
X_transformed = pt.fit_transform(X)
```

### Example
```python
>>> X = [[1], [2], [3], [100]]  # Skewed data
>>> pt = PowerTransformer(method='yeo-johnson')
>>> X_transformed = pt.fit_transform(X)
>>> # Now more normally distributed
```

### Task
Apply Yeo-Johnson power transformation to make skewed data more Gaussian. Store in `X_power`.

### Expected Properties
- `X_power` should be a numpy array
- Should have same shape as input (7, 1)
- Data should be more normally distributed than original

In [ ]:
# Your solution:
# Skewed data
X = np.array([[1], [2], [3], [4], [5], [100], [200]])

X_power = None

In [ ]:
# Verification
check.is_not_none(X_power, "P17: Not None")
check.is_type(X_power, np.ndarray, "P17: Type check")
check.has_shape(X_power, (7, 1), "P17: Correct shape")

---
## Summary

Run this cell to see your overall progress on this notebook.

In [ ]:
check.summary()